function AB_inv = AB_inv_fct(alpha,beta,gamma)
%AB_INV_FCT
%    AB_INV = AB_INV_FCT(ALPHA,BETA,GAMMA)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    12-Nov-2019 11:06:31

t2 = cos(beta);
t3 = cos(gamma);
t4 = sin(beta);
t5 = sin(gamma);
t6 = 1.0./t2;
AB_inv = reshape([t3.*t6,-t5,t3.*t4.*t6,t5.*t6,t3,t4.*t5.*t6,0.0,0.0,1.0],[3,3]);
