function b = b_fct(x,y,phi,dx,dy,dphi,m,theta,grav,d)
%B_FCT
%    B = B_FCT(X,Y,PHI,DX,DY,DPHI,M,THETA,GRAV,D)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    19-Feb-2020 13:10:44

t2 = cos(phi);
t3 = sin(phi);
t4 = dphi.^2;
b = [0.0;m.*(-9.81e+2./1.0e+2);0.0;dphi.*dx.*t2.*2.0+dphi.*dy.*t3.*2.0-t3.*t4.*x+t2.*t4.*y];
