function CoGs = CoGPositions(gamma,alpha,l_0,l2x,l2y,rFoot,gx,gy,m1,m2,j2)
%COGPOSITIONS
%    COGS = COGPOSITIONS(GAMMA,ALPHA,L_0,L2X,L2Y,RFOOT,GX,GY,M1,M2,J2)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    10-Apr-2011 10:49:54

t764 = sin(gamma);
t765 = l_0-rFoot;
t766 = alpha+gamma;
t767 = cos(gamma);
t768 = t765.*t767;
t769 = cos(t766);
t770 = sin(t766);
CoGs = reshape([-gamma.*rFoot-t764.*t765,rFoot+t768,0.0,-gamma.*rFoot+l2x.*t764+l2y.*t767-t764.*t765,rFoot+t768-l2x.*t767+l2y.*t764,gamma,-gamma.*rFoot+l2x.*t770+l2y.*t769-t764.*t765,rFoot+t768-l2x.*t769+l2y.*t770,t766],[3, 3]);
