function footPts = FootPtPositions(gamma,alpha,l_0,l2x,l2y,rFoot,gx,gy,m1,m2,j2)
%FOOTPTPOSITIONS
%    FOOTPTS = FOOTPTPOSITIONS(GAMMA,ALPHA,L_0,L2X,L2Y,RFOOT,GX,GY,M1,M2,J2)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    10-Apr-2011 10:49:54

t778 = l_0-rFoot;
t779 = alpha+gamma;
footPts = reshape([-gamma.*rFoot,rFoot,-gamma.*rFoot-t778.*sin(gamma)+t778.*sin(t779),rFoot+t778.*cos(gamma)-t778.*cos(t779)],[2, 2]);
