function links = LinkPositions(gamma,alpha,l_0,l2x,l2y,rFoot,gx,gy,m1,m2,j2)
%LINKPOSITIONS
%    LINKS = LINKPOSITIONS(GAMMA,ALPHA,L_0,L2X,L2Y,RFOOT,GX,GY,M1,M2,J2)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    10-Apr-2011 10:49:54

t772 = l_0-rFoot;
t773 = sin(gamma);
t774 = alpha+gamma;
t775 = cos(gamma);
t776 = t772.*t775;
links = reshape([-gamma.*rFoot,rFoot,-gamma.*rFoot-t772.*t773,rFoot+t776,-gamma.*rFoot-t772.*t773+t772.*sin(t774),rFoot+t776-t772.*cos(t774)],[2, 3]);
