function A_IC = A_IC_fct(alpha,beta,gamma)
%A_IC_FCT
%    A_IC = A_IC_FCT(ALPHA,BETA,GAMMA)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    12-Nov-2019 11:06:32

t2 = cos(alpha);
t3 = cos(beta);
t4 = cos(gamma);
t5 = sin(alpha);
t6 = sin(beta);
t7 = sin(gamma);
A_IC = reshape([t3.*t4,t3.*t7,-t6,-t2.*t7+t4.*t5.*t6,t2.*t4+t5.*t6.*t7,t3.*t5,t5.*t7+t2.*t4.*t6,-t4.*t5+t2.*t6.*t7,t2.*t3],[3,3]);
