function C3_omega_IC3 = C3_omega_IC3_fct(alpha,beta,gamma,alpha_dot,beta_dot,gamma_dot)
%C3_OMEGA_IC3_FCT
%    C3_OMEGA_IC3 = C3_OMEGA_IC3_FCT(ALPHA,BETA,GAMMA,ALPHA_DOT,BETA_DOT,GAMMA_DOT)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    02-Jan-2019 11:17:36

t2 = cos(alpha);
t3 = cos(beta);
t4 = sin(alpha);
t5 = beta_dot.*t4;
t6 = beta_dot.*t2;
t7 = gamma_dot.*t3.*t4;
t8 = sin(beta);
t9 = gamma_dot.*t8;
C3_omega_IC3 = reshape([0.0,-t5+gamma_dot.*t2.*t3,-t6-t7,t5-gamma_dot.*t2.*t3,0.0,alpha_dot-t9,t6+t7,-alpha_dot+t9,0.0],[3,3]);
